server:
  port: 9090
spring:  datasource:    driver-class-name: com.amazon.redshift.jdbc42.Driver
    url: jdbc:redshift://shiva-db-instance.cmeccjkifqph.us-east-1.redshift.amazonaws.com:5439/dev
    username: root
    password: Password1  jpa:    properties:      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
    show-sql: true
#logging:#  level:#    org:
#      springframework: INFO    

    